name: Build and Test

on:
  pull_request:
  # push:
  #   branches:
  #     - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build-and-test-ubuntu:
    runs-on:  ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Ipopt
      run: apt update && apt install -y --no-install-recommends coinor-libipopt-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
